site_name: BYU CCE 270
nav:
  - Unit 1:
    - Lookups and Match:
      - Reading: unit1/fill/filler.md
      - In Class: unit1/fill/filler.md
      - Homework: unit1/homework/lookups_and_match.md
    - Variables:
      - Reading: homework/variables.md
      - In Class: homework/lists.md
      - Homework: exercises/variables.md
theme:
  name: readthedocs
