site_name: BYU CCE 270
site_url: https://byu-cce270.readthedocs.io/en/latest/
site_description: Course materials for CCE 270 at BYU
site_author: Instructors and TAs of CCE 270 at BYU
repo_url: https://github.com/byu-cce270/content/
favicon: 'images/favicon.ico'
theme:
  name: null
  custom_dir: 'cinder'
nav:
  - Home: index.md
  - Unit 1:
    - A Tour of Class Resources: unit1/0_getting_started/day1_hw.md
    - Lookups, Match, Data Validation, and Conditional Formatting:
        - Reading: unit1/1_lookup_match/lookmat_read.md
        - In Class: unit1/1_lookup_match/lookmat_class.md
        - Homework: unit1/1_lookup_match/lookmat_hw.md
    - Analyzing and Managing Data:
        - Reading: unit1/2_analyzing_managing_data/data_read.md
        - In Class: unit1/2_analyzing_managing_data/data_class.md
        - Homework: unit1/2_analyzing_managing_data/data_hw.md
    - If Statements and Goal Seek:
      - Reading: unit1/3_if_goalseek/ifgs_read.md
      - In Class: unit1/3_if_goalseek/ifgs_class.md
      - Homework: unit1/3_if_goalseek/ifgs_hw.md
    - Pivot Table and Query Function:
      - Reading: unit1/4_pivot_querey/pivquer_read.md
      - In Class: unit1/4_pivot_querey/pivquer_class.md
      - Homework: unit1/4_pivot_querey/pivquer_hw.md
    - Pivot Table and Query Function:
        - Reading: unit1/5_grantt_charts/grantt_read.md
        - In Class: unit1/5_grantt_charts/grantt_class.md
        - Homework: unit1/5_grantt_charts/grantt_hw.md

  - Unit 2:
    - Introduction to Python and Variables:
      - Reading: unit2/0_intro_python_variables/into_var_read.md
      - Homework: unit2/0_intro_python_variables/into_var_hw.md
    - Variables:
      - Reading: unit2/reading/variables.md
      - In Class: unit2/exercises/variables.md
      - Homework: unit2/homework/variables.md
    - Lists:
      - Reading: unit2/reading/lists.md
      - In Class: unit2/homework/lists.md
      - Homework: unit2/exercises/lists.md
    - Dictionaries:
      - Homework: unit2/dictionaries/dict_homework.md
    - Functions (Part 2):
      - Homework: unit2/7b_functions/functions_hw.md
