site_name: BYU CCE 270
nav:
  - Homework:
      - Variables: homework/variables.md
      - Lists: homework/lists.md
  - Exercises:
      - Variables: exercises/variables.md
      - Lists: exercises/lists.md
theme:
  name: readthedocs
