site_name: BYU CCE 270
nav:
  - Unit 1:
    - Lookups and Match:
      - Homework: unit1/homework/lookups_and_match.md
    - Variables:
      - Reading: homework/variables.md
      - In Class: homework/lists.md
      - Homework: exercises/variables.md
    - Query Function:
      - Reading: reading/query_function.md
      - In Class: homework/query_function.md
      - Homework: exercises/query_function.md
theme:
  name: readthedocs
