site_name: BYU CCE 270
nav:
  - Home: index.md
  - 'Unit 1':
    - 'Lookups and Match':
      - 'Homework': 'unit1/homework/lookups_and_match.md'
    - 'Variables':
      - 'Reading': 'homework/variables.md'
      - 'In Class': 'homework/lists.md'
      - 'Homework': 'exercises/variables.md'
    - 'Query Function':
      - 'Reading': 'unit1/reading/query_function.md'
      - 'In Class': 'unit1/homework/query_function.md'
      - 'Homework': 'unit1/exercises/query_function.md'
theme:
  name: mkdocs
