site_name: BYU CCE 270
site_url: https://byu-cce270.readthedocs.io/en/latest/
site_description: Course materials for CCE 270 at BYU
site_author: Instructors and TAs of CCE 270 at BYU
repo_url: https://github.com/byu-cce270/content/
#favicon: 'images/favicon.ico'
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js
  - js/mathjax-config.js
extra_css:
  - css/custom.css
markdown_extensions:
    - attr_list
    - sane_lists
    - md_in_html
    - admonition
    - pymdownx.arithmatex:
        generic: true
theme: readthedocs
nav:
  - Home: index.md
  - Class Resources:
    - Textbooks: resources/textbooks/textbooks.md
    - Teaching Assistants (TAs): resources/ta/tas.md
    - Office Hours: resources/ta/ta_hours.md
    - Grading Policy: resources/ta/grading_policy.md
  - Unit 1 - Spreadsheet:
    - Review - Cells and Formulas: unit1/0_cells_and_formulas_review/pre_class_review.md
    - A Tour of Class Resources: unit1/0_getting_started/day1_hw.md
    - Analyzing/Managing Data, Conditional Formatting:
        - Reading: unit1/1_analyzing_managing_data/data_read.md
        - In Class: unit1/1_analyzing_managing_data/data_class.md
        - Homework: unit1/1_analyzing_managing_data/data_hw.md
    - Lookups, Match, and IF Functions:
        - Reading: unit1/2_lookup_match_if/lookmatif_read.md
        - In Class: unit1/2_lookup_match_if/lookmatif_class.md
        - Homework: unit1/2_lookup_match_if/lookmatif_hw.md
    - Pivot Tables, Goal Seek, and Data Validation:
      - Reading: unit1/3_pivot_goalseek/pivgolseek_read.md
      - In Class: unit1/3_pivot_goalseek/pivgolseek_class.md
      - Homework: unit1/3_pivot_goalseek/pivgolseek_hw.md
    - Graphing and Numerical Solver:
      - Reading: unit1/4_graphing_numsolver/graphsolver_read.md
      - In Class: unit1/4_graphing_numsolver/graphsolver_class.md
      - Homework: unit1/4_graphing_numsolver/graphsolver_hw.md
    - Gantt Chart, Project Scheduling and Tracking:
        - Reading: unit1/5_gantt_charts/gantt_read.md
        - In Class: unit1/5_gantt_charts/gantt_class.md
        - Homework: unit1/5_gantt_charts/gantt_hw.md
    - Unit 1 Project:
        - Project Prompt: unit1/6_unit1_project/u1_pro_promt.md

  - Unit 2 - Intro to Python:
    - Introduction to Python and Variables:
        - Reading: unit2/00_intro_python_variables/into_var_read.md
        - In Class: unit2/00_intro_python_variables/into_var_class.md
        - Homework: unit2/00_intro_python_variables/into_var_hw.md
    - Introducing Lists:
        - Reading: unit2/01_introducing_lists/lists_read.md
        - In Class: unit2/01_introducing_lists/lists_class.md
        - Homework: unit2/01_introducing_lists/lists_hw.md
    - Working with Lists (For Loops):
        - Reading: unit2/02_for_loops_into_functions/for_read.md
        - In Class: unit2/02_for_loops_into_functions/for_class.md
        - Homework: unit2/02_for_loops_into_functions/for_hw.md
    - IF Statements:
        - Reading: unit2/03_if_statements/if_read.md
        - In Class: unit2/03_if_statements/if_class.md
        - Homework: unit2/03_if_statements/if_hw.md
    - Dictionaries:
        - Reading: unit2/04_dictionaries/dict_read.md
        - In Class: unit2/04_dictionaries/dict_class.md
        - Homework: unit2/04_dictionaries/dict_hw.md
    - While Loops:
        - Reading: unit2/05_while_loops/while_read.md
        - In Class: unit2/05_while_loops/while_class.md
        - Homework: unit2/05_while_loops/while_hw.md
    - Functions (Part 1):
        - Reading: unit2/06a_functions/functions1_read.md
        - In Class: unit2/06a_functions/functions1_class.md
        - Homework: unit2/06a_functions/functions1_hw.md
    - Functions (Part 2):
        - Reading: unit2/06b_functions/functions2_read.md
        - In Class: unit2/06b_functions/functions2_class.md
        - Homework: unit2/06b_functions/functions2_hw.md

  - Unit 3 - Advanced Python:
    - Reading and Writing Files:
        - Reading: unit3/00_files/file_read.md
        - In Class: unit3/00_files/file_class.md
        - Homework: unit3/00_files/file_hw.md
    - Gspread and APIs:
        - Reading: unit3/01_gspread/gspread_read.md
        - In Class: unit3/01_gspread/gspread_class.md
        - Homework: unit3/01_gspread/gspread_hw.md
    - MatPlotLib:
        - Reading: unit3/02_matplotlib/matplot_read.md
        - In Class: unit3/02_matplotlib/matplot_class.md
        - Homework: unit3/02_matplotlib/matplot_hw.md
    - Numpy:
        - Reading: unit3/03_numpy/numpy_read.md
        - In Class: unit3/03_numpy/numpy_class.md
        - Homework (v1): unit3/03_numpy/numpy_hw.md
        - Homework (v2): unit3/03_numpy/numpy_hw2.md
    - Pandas (Part 1):
        - Reading: unit3/04_pandas_part1/pandas1_read.md
        - In Class: unit3/04_pandas_part1/pandas1_class.md
        - Homework: unit3/04_pandas_part1/pandas1_hw.md
    - Pandas (Part 2):
        - Reading: unit3/05_pandas_part2/pandas2_read.md
        - In Class: unit3/05_pandas_part2/pandas2_class.md
        - Homework: unit3/05_pandas_part2/pandas2_hw.md
#    - Python and Excel:
#        - Reading: unit3/python_and_excel/excel_read.md
#        - In Class: unit3/python_and_excel/excel_class.md
#        - Homework: unit3/python_and_excel/excel_hw.md
    - ipywidgets:
        - Reading: unit3/06_ipywidgets/ipy_read.md
        - In Class: unit3/06_ipywidgets/ipy_class.md
        - Homework: unit3/06_ipywidgets/ipy_hw.md
    - Final Project:
        - Project Proposal: unit3/07_final_project/final_pro_proposal.md
        - Project Prompt: unit3/07_final_project/final_pro_prompt.md
  - Bonus Content:
    - Python and Excel: bonus/python_and_excel/excel_read.md
    - Using Python Locally: bonus/python_local/local_read.md
